package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/sathomsen/slidetell/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Skill)
// DB Table: Plural (skills)
// Resource: Plural (Skills)
// Path: Plural (/skills)
// View Template Folder: Plural (/templates/skills/)

// SkillsResource is the resource for the Skill model
type SkillsResource struct {
	buffalo.Resource
}

// List gets all Skills. This function is mapped to the path
// GET /skills
func (v SkillsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	skills := &models.Skills{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Skills from the DB
	if err := q.All(skills); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, skills))
}

// Show gets the data for one Skill. This function is mapped to
// the path GET /skills/{skill_id}
func (v SkillsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Skill
	skill := &models.Skill{}

	// To find the Skill the parameter skill_id is used.
	if err := tx.Find(skill, c.Param("skill_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, skill))
}

// New renders the form for creating a new Skill.
// This function is mapped to the path GET /skills/new
func (v SkillsResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Skill{}))
}

// Create adds a Skill to the DB. This function is mapped to the
// path POST /skills
func (v SkillsResource) Create(c buffalo.Context) error {
	// Allocate an empty Skill
	skill := &models.Skill{}

	// Bind skill to the html form elements
	if err := c.Bind(skill); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(skill)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, skill))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Skill was created successfully")

	// and redirect to the skills index page
	return c.Render(201, r.Auto(c, skill))
}

// Edit renders a edit form for a Skill. This function is
// mapped to the path GET /skills/{skill_id}/edit
func (v SkillsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Skill
	skill := &models.Skill{}

	if err := tx.Find(skill, c.Param("skill_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, skill))
}

// Update changes a Skill in the DB. This function is mapped to
// the path PUT /skills/{skill_id}
func (v SkillsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Skill
	skill := &models.Skill{}

	if err := tx.Find(skill, c.Param("skill_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Skill to the html form elements
	if err := c.Bind(skill); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(skill)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, skill))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Skill was updated successfully")

	// and redirect to the skills index page
	return c.Render(200, r.Auto(c, skill))
}

// Destroy deletes a Skill from the DB. This function is mapped
// to the path DELETE /skills/{skill_id}
func (v SkillsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Skill
	skill := &models.Skill{}

	// To find the Skill the parameter skill_id is used.
	if err := tx.Find(skill, c.Param("skill_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(skill); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Skill was destroyed successfully")

	// Redirect to the skills index page
	return c.Render(200, r.Auto(c, skill))
}
